name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build source code
        run: |
         mkdir -p cmake_build && \
         cd ./cmake_build && \
         cmake .. && \
         make
      - name: Run with normal input
        run: |
         cd ./cmake_build && \
         setarch `uname -m` -R ./main < ./test/normal_input.txt
      - name: Run with hacker input
        run: |
         cd ./cmake_build && \
         setarch `uname -m` -R ./main < ./test/hacker_input.txt
         true

